# Generated by Django 2.0.6 on 2019-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_registapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Salary', models.FloatField()),
            ],
        ),
    ]
