# Generated by Django 2.0.6 on 2019-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_registapp', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headpic',
            field=models.ImageField(null=True, upload_to='picspy'),
        ),
    ]
