# Generated by Django 2.0.6 on 2019-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_registapp', '0003_user_headpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='headpic',
        ),
        migrations.AddField(
            model_name='staff',
            name='headpic',
            field=models.ImageField(null=True, upload_to='picspy'),
        ),
    ]
