# Generated by Django 2.0.6 on 2019-05-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_registapp', '0006_auto_20190526_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='headpic',
            new_name='Headpic',
        ),
    ]
